export enum ROUTES {
	AUTH = 'auth',
	ADMIN = 'admin',
	ROLES = 'roles',
	// CLINIC,
	// CLINIC_ACCOUNT,
	// CLINIC_APPOINTMENT,
	// CLINIC_AVATAR,
	// CLINIC_DEPARTMENT,
	// CLINIC_DEPARTMENT_DOCTOR,
	// CLINIC_DOCTOR,
	// CLINIC_DOCTOR_WORKING_SCHEDULE,
	// CLINIC_FILE,
	// CLINIC_MEDICAL_SERVICES,
	// CLINIC_PATIENT,
	// CLINIC_PROMOTION,
	// CLINIC_PROMOTION_PHOTO,
	// CLINIC_PROMOTION_ANALYTIC,
	// CLINIC_PROMOTION_DOCTOR,
	// CLINIC_RATING,
	// CLINIC_RATINGS_VIA_GOOGLE,
	// APP_INBOX,
	// APP_SESSION,
	// APP_TRAFFICS,
}

export const resolveAPI = (route: ROUTES) => {
	return `${route}`
}
